[project]
name = "frida"
version = "0.0.1"
description = "Generate frida hook script!"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "loguru>=0.7.3",
    "mcp[cli]>=1.9.1",
    "pyqt5>=5.15.11",
]
